---
title: "Mapping"
output: html_document
---

```{r}
library(tidyverse)
library(leaflet)
library(ggplot2)
library(tigris)
library(plotly)
```

Read in wine data.

```{r extract_year_function}
year_extract <- function(string) {
  t <- regmatches(string, regexec("[1-2][9|0][0-9][0-9]", string))
  sapply(t, function(x) {
    if (length(x) > 0) {
      return(as.numeric(x))
    } else {
      return(NA)    
    }
  })
}
```

```{r geocoding}
wine_tidy_df = 
  read_csv(
  "./wine_data/winemag-data-130k-v2.csv") %>% 
  janitor::clean_names() %>% 
  select(-region_2, -taster_twitter_handle, -taster_name, -x1) %>% 
  mutate(year = year_extract(title)) 

wine_by_country = wine_tidy_df %>% 
 mutate(
   country = recode(country, US = "United States")
 ) %>% 
  group_by(country) %>% 
  drop_na(country) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  rename(
    total = n) %>% 
  mutate(total = as.numeric(total)) %>% 
  view

wine_us = wine_tidy_df %>% 
  filter(country == "US") %>% 
  group_by(province) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  rename(
    state = province,
    total = n) %>% 
  mutate(total = as.numeric(total)) %>% 
  view
```

```{r choropleth_map}
states <- states(cb = TRUE)

states %>% 
  leaflet() %>% 
  addTiles() %>% 
  addPolygons(popup = ~NAME)

states_merged_wine <- geo_join(states, wine_us, "NAME", "state")

mybins <- c(0,100,1000,8000,10000,40000)
mypal <- colorBin(palette = "Purples", domain = states_merged_wine$total, na.color = "transparent", bins = mybins)

states_merged_wine <- subset(states_merged_wine, !is.na(total))

popup <- paste0("Wineries: ", as.character(states_merged_wine$total))

states_merged_wine %>% 
  leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(
    fillColor = ~mypal(total), 
    fillOpacity = 1.0, 
    weight = 0.4, 
    smoothFactor = 0.2, 
    popup = ~popup) %>% 
  addLegend(pal = mypal, 
            values = states_merged_wine$total, 
            position = "bottomright", 
            title = "Wineries")
```

```{r world_choropleth}
wine_by_country

library(rgdal)

world_spdf <- readOGR( 
  dsn = paste0(getwd(),"/wine_data/world_shape_file/") , 
  layer = "TM_WORLD_BORDERS_SIMPL-0.3",
  verbose = FALSE
)

world_spdf %>% 
  leaflet() %>% 
  addTiles() %>% 
  addPolygons(popup = ~NAME)

countries_merged_wine <- geo_join(world_spdf, wine_by_country, "NAME", "country")

world_bins <- c(0,100,1000,10000,20000,30000,60000)
world_pal <- colorBin(palette = "Reds", domain = countries_merged_wine$total, na.color = "transparent", bins = world_bins)

countries_merged_wine <- subset(countries_merged_wine, !is.na(total))

world_popup <- paste0("Wineries: ", as.character(countries_merged_wine$total))

countries_merged_wine %>% 
  leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(
    fillColor = ~world_pal(total), 
    fillOpacity = 1.0, 
    weight = 0.4, 
    smoothFactor = 0.2, 
    popup = ~world_popup) %>% 
  addLegend(pal = world_pal, 
            values = countries_merged_wine$total, 
            position = "bottomright", 
            title = "Wineries")
```

