---
title: ""
output: 
  html_document:
    toc: true
    toc_float: true
---


#### Exploratory analysis

```{r}
library(tidyverse)
library(modelr)
library(mgcv)
```


```{r}
red_df =  read_csv("./wine_data/tidy/wine_red.csv")
white_df = read_csv("./wine_data/tidy/wine_white.csv") 

red_df_reg =
  red_df %>%
  filter(year>=2000) %>%
  mutate(
         bold = str_detect(description, "bold"),
         tannis = str_detect(description, "tanni"),
         dry = str_detect(description, "dry"),
         acidic = str_detect(description, "acidi"),
         price_cp1 = (price > 100) * (price - 100),
         price_cp2 = (price < 30) * (price - 30)
    )

white_df_reg = 
  white_df %>%
  filter(year>=2000) %>%
  mutate(price_cp1 = (price > 100) * (price - 100),
         price_cp2 = (price < 30) * (price - 30))
```

## Fit models for red wine points

```{r}
fit_1 = lm(points ~ price + year + bold + tannis + dry + acidic
           , 
           data = red_df_reg)

fit_1 %>% 
  broom::tidy()
```

```{r}
linear_mod_red = lm(points ~ price, data = red_df_reg)

pwl_mod_red = lm(points ~ price + price_cp1 + price_cp2,  data = red_df_reg)

smooth_mod_red = gam(points ~ s(price), data = red_df_reg)
```



## Fit models for white wine points

```{r}
fit_2 = lm(points ~ price + year, data = white_df_reg)

fit_2 %>% 
  broom::tidy()

linear_mod_white = lm(points ~ price, data = white_df_reg)

pwl_mod_white = lm(points ~ price + price_cp1 + price_cp2,  data = white_df_reg)

smooth_mod_white = gam(points ~ s(price), data = white_df_reg)
```
```{r}
red_df_reg %>%
  filter(price >= 100) %>%
  ggplot(aes (x = price, y = points, color = country))+ 
  geom_point()

white_df_reg %>%
  filter(price >= 100) %>%
  ggplot(aes (x = price, y = points, color = country))+ 
  geom_point()

white_df_reg %>%
  filter(points > 84) %>%
  ggplot(aes (x = country, y = price))+ 
  geom_boxplot()

```

Plot the 3 models with residuals

```{r}
library("patchwork")

a =
  red_df_reg %>% 
  gather_predictions(linear_mod_red, pwl_mod_red, smooth_mod_red) %>%
  mutate(model = fct_inorder(model)) %>%
  ggplot(aes(x = price, y = points)) + 
  geom_point(alpha = .05) +
  geom_line(aes(y = pred), color = "dark red") + 
  facet_grid(~model)
  
b = 
  white_df_reg %>% 
  gather_predictions(linear_mod_white, pwl_mod_white, smooth_mod_white) %>%
  mutate(model = fct_inorder(model)) %>%
  ggplot(aes(x = price, y = points)) + 
  geom_point(alpha = .05) +
  geom_line(aes(y = pred), color = "yellow") + 
  facet_grid(~model)


a

b
```

```{r}
# white_cv_df =
#   crossv_mc(white_df_reg, 100) %>% 
#   mutate(
#     train = map(train, as_tibble),
#     test = map(test, as_tibble))

# white_cv_df = 
#   white_cv_df %>% 
#   mutate(
#     linear_mod  = map(train, ~lm(points ~ price, data = .price)),
#     pwl_mod     = map(train, ~lm(armc ~ weight + weight_cp, data = .x)),
#     smooth_mod  = map(train, ~gam(armc ~ s(weight), data = as_tibble(.x)))) %>% 
#   mutate(
#     rmse_linear = map2_dbl(linear_mod, test, ~rmse(model = .x, data = .y)),
#     rmse_pwl    = map2_dbl(pwl_mod, test, ~rmse(model = .x, data = .y)),
#     rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y)))
# 
```

