---
title: "Word Cloud"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r message = FALSE}
library(tidyverse)
library(plotly)
library(tidytext)
library(RColorBrewer)
library(tidytext)
library(wordcloud2)
library(knitr)
library(webshot)
library("htmlwidgets")
```


```{r subset, message = FALSE, warning = FALSE}
# Read in tidy wine data and generate subsets for new world, old world, higher-rating (>=90), and lower-rating (<90) wines.
wine_df = read_csv("./wine_data/tidy/wine_all.csv")
red_df =  read_csv("./wine_data/tidy/wine_red.csv")
white_df = read_csv("./wine_data/tidy/wine_white.csv")
rose_df = read_csv("./wine_data/tidy/wine_rose.csv")
sparkling_df = read_csv("./wine_data/tidy/wine_sparkling.csv")

new_red = red_df %>% filter(new_world == TRUE)
old_red = red_df %>% filter(old_world == TRUE)
new_white = white_df %>% filter(new_world == TRUE)
old_white = white_df %>% filter(old_world == TRUE)
new_rose = rose_df %>% filter(new_world == TRUE)
old_rose = rose_df %>% filter(old_world == TRUE)
new_sparkling = sparkling_df %>% filter(new_world == TRUE)
old_sparkling = sparkling_df %>% filter(old_world == TRUE)

high_wine = wine_df %>% filter(points >= 90)
low_wine = wine_df %>% filter(points < 90)
high_red = red_df %>% filter(points >= 90)
low_red = red_df %>% filter(points < 90)
high_white = white_df %>% filter(points >= 90)
low_white = white_df %>% filter(points < 90)
high_rose = rose_df %>% filter(points >= 90)
low_rose = rose_df %>% filter(points < 90)
high_sparkling = sparkling_df %>% filter(points >= 90)
low_sparkling = sparkling_df %>% filter(points < 90)
```

# Top 10 wine notes for each type

```{r top10, message = FALSE}
wine_top10_word <- function(wine_subset){
  # reshape the .txt data frame into one column
  wine_word = 
    wine_subset %>% 
    select(description) %>% 
    unnest_tokens(word, description) %>% 
    dplyr::count(word, sort = TRUE) %>% 
    ungroup()
  
  # remove uninformative words
  data("stop_words")
  wine_word = 
    anti_join(wine_word, stop_words)
  
  # remove more uninformative words in our study
  other_meaningless <- data.frame(word = c("style", "character", "vineyard", "wine","drink","flavors", "notes","note", "finish", "structure", "blend", "mouth", "touch", "feels", "offers", "nose", "age",  "palate", "cabernet", "pinot","noir", "chardonnay", "sauvignon", "aromas", "yellow", "green","black", "red", "white", "rose", "rosé", "sparkling"))
  wine_word = 
    wine_word %>% 
    anti_join(other_meaningless, by = "word")
  
  # remove numbers
  nums = wine_word %>% filter(str_detect(word, "^[0-9]")) %>% select(word) %>% unique()
  wine_word = wine_word %>% 
    anti_join(nums, by = "word")
  
  # check the top 10 words
  wine_word %>% head(10) %>% as_tibble()
}

red_top10 <- wine_top10_word(red_df)[,1] %>% rename(red = word)
white_top10 <- wine_top10_word(white_df)[,1]  %>% rename(white = word)
rose_top10 <- wine_top10_word(rose_df)[,1]  %>% rename(rose = word)
sparkling_top10 <- wine_top10_word(sparkling_df)[,1]  %>% rename(sparkling = word)
as_tibble(c(red_top10, white_top10, rose_top10, sparkling_top10)) %>% 
  mutate(rank = 1:n()) %>% 
  select(rank, red:sparkling) %>% 
  knitr::kable()
```

# Word Cloud
```{r wordcloud, message = FALSE}
# Create word cloud for each type (red, white, rose, and sparkling)
wine_word_cloud <- function(wine_subset, color1, color2) {
  # reshape the .txt data frame into one column
  wine_word = 
    wine_subset %>% 
    select(description) %>% 
    unnest_tokens(word, description) %>% 
    dplyr::count(word, sort = TRUE) %>% 
    ungroup()
  
  # remove uninformative words
  data("stop_words")
  wine_word = 
    anti_join(wine_word, stop_words)
  
  # remove more uninformative words in our study
  other_meaningless <- data.frame(word = c("style", "character", "vineyard", "wine","drink","flavors", "notes","note", "finish", "structure", "blend", "mouth", "touch", "feels", "offers", "nose", "age",  "palate", "cabernet", "pinot","noir", "chardonnay", "sauvignon", "aromas", "yellow", "green","black", "red", "white", "rose", "rosé", "sparkling"))
  wine_word = 
    wine_word %>% 
    anti_join(other_meaningless, by = "word")
  
  # remove numbers
  nums = wine_word %>% filter(str_detect(word, "^[0-9]")) %>% select(word) %>% unique()
  wine_word = wine_word %>% 
    anti_join(nums, by = "word")
  
  # plot word cloud
  wine_word %>% head(100) %>% 
    wordcloud2(size = 0.58, color = color1, backgroundColor = color2)
}
```

## All types
```{r message = FALSE}
wine_word_cloud(wine_df, "red", "white")
```

### (1) Higher-rating (>=90)
```{r message = FALSE}
wine_word_cloud(high_wine, "blue", "white")
```

### (2) Lower-rating (<90)
```{r message = FALSE}
wine_word_cloud(low_wine, "green", "white")
```

## Red wine
```{r message = FALSE}
red_word <- wine_word_cloud(red_df, "8D021F", "white")
red_word
```

### (1) New-world red wine
```{r message = FALSE}
wine_word_cloud(new_red, "#A1045A", "white")
```

### (2) Old-world red wine
```{r message = FALSE}
wine_word_cloud(old_red, "#67032F", "white")
```

## White wine
```{r message = FALSE}
white_word <- wine_word_cloud(white_df, "FEDC56", "white")
white_word
```

### (1) New-world white wine
```{r message = FALSE}
wine_word_cloud(new_white, "#F9E076", "white")
```

### (2) Old-world white wine
```{r message = FALSE}
wine_word_cloud(old_white, "D2B55B", "white")
```

## Rose
```{r message = FALSE}
rose_word <- wine_word_cloud(rose_df, "E75480", "white")
rose_word
```

## Sparkling
```{r message = FALSE}
sparkling_word <- wine_word_cloud(sparkling_df, "F5B799", "white")
sparkling_word
```


```{r export, include = FALSE}
saveWidget(red_word, "tmp1.html", selfcontained = F)
webshot("tmp1.html", "./image/red_word.png", delay = 5, vwidth = 500, vheight = 500)

saveWidget(white_word, "tmp2.html", selfcontained = F)
webshot("tmp2.html", "./image/white_word.png", delay = 5, vwidth = 500, vheight = 500)

saveWidget(rose_word, "tmp3.html", selfcontained = F)
webshot("tmp3.html", "./image/rose_word.png", delay = 5, vwidth = 500, vheight = 500)

saveWidget(sparkling_word, "tmp4.html", selfcontained = F)
webshot("tmp4.html", "./image/sparkling_word.png", delay = 5, vwidth = 500, vheight = 500)

file.remove("tmp1.html")
file.remove("tmp2.html")
file.remove("tmp3.html")
file.remove("tmp4.html")


unlink("tmp1_files", recursive = TRUE)
unlink("tmp2_files", recursive = TRUE)
unlink("tmp3_files", recursive = TRUE)
unlink("tmp4_files", recursive = TRUE)

```


